/*
  A map of country codes to an ordered list of official / preferred languages.
  (Only countries with more than one language is needed right now)
  Source: https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes
*/

const data = {
  af: ["fa", "ps"],
  aq: ["en", "es", "fr", "ru"],
  as: ["en", "sm"],
  aw: ["nl", "pap"],
  ba: ["bs", "hr", "sr"],
  be: ["nl", "fr", "de"],
  bo: ["es", "qu", "gn", "ay"],
  bw: ["en", "tn"],
  by: ["be", "ru"],
  ca: ["en", "fr"],
  cf: ["fr", "sg"],
  ch: ["de", "fr", "it", "rm"],
  ck: ["en", "rar"],
  cm: ["fr", "en"],
  cw: ["nl", "en"],
  cy: ["el", "tr"],
  dj: ["fr", "ar", "so", "aa"],
  eh: ["ar", "es", "fr"],
  er: ["ti", "ar", "en"],
  es: ["ast", "ca", "es", "eu", "gl"],
  et: ["am", "om"],
  fi: ["fi", "sv", "se"],
  fo: ["fo", "da"],
  gb: ["en", "ga", "cy", "gd", "kw"],
  gl: ["kl", "da"],
  gq: ["es", "fr", "pt"],
  gu: ["en", "ch"],
  hk: ["zh-hant", "en"],
  ht: ["fr", "ht"],
  ie: ["en", "ga"],
  in: ["hi", "en"],
  iq: ["ar", "ku"],
  it: ["it", "de", "fr"],
  ke: ["sw", "en"],
  kg: ["ky", "ru"],
  km: ["ar", "fr", "sw"],
  kz: ["kk", "ru"],
  lb: ["ar", "fr"],
  lk: ["si", "ta"],
  ls: ["en", "st"],
  lu: ["lb", "fr", "de"],
  ma: ["ar", "fr", "zgh"],
  md: ["ro", "ru", "uk"],
  me: ["srp", "sr", "hr", "bs", "sq"],
  mg: ["mg", "fr"],
  mh: ["en", "mh"],
  mo: ["zh-hant", "pt"],
  mp: ["en", "ch"],
  mr: ["ar", "fr"],
  mt: ["mt", "en"],
  mu: ["mfe", "fr", "en"],
  mw: ["en", "ny"],
  na: ["en", "sf", "de"],
  nf: ["en", "pih"],
  no: ["nb", "nn", "no", "se"],
  nr: ["na", "en"],
  nu: ["niu", "en"],
  nz: ["mi", "en"],
  pg: ["en", "tpi", "ho"],
  ph: ["en", "tl"],
  pk: ["en", "ur"],
  pn: ["en", "pih"],
  pr: ["es", "en"],
  ps: ["ar", "he"],
  pw: ["en", "pau", "ja", "sov", "tox"],
  py: ["es", "gn"],
  rs: ["sr", "sr-Latn"],
  rw: ["rw", "fr", "en"],
  sc: ["fr", "en", "crs"],
  sd: ["ar", "en"],
  sg: ["zh-hans", "en", "ms", "ta"],
  so: ["so", "ar"],
  sx: ["nl", "en"],
  sz: ["en", "ss"],
  td: ["fr", "ar"],
  tj: ["tg", "ru"],
  tk: ["tkl", "en", "sm"],
  tl: ["pt", "tet"],
  tn: ["ar", "fr"],
  tz: ["sw", "en"],
  ug: ["en", "sw"],
  uz: ["uz", "kaa"],
  vu: ["bi", "en", "fr"],
  ws: ["sm", "en"],
  xk: ["en", "af"],
  za: ["en", "af", "st", "tn", "xh", "zu"],
  zw: ["en", "sn", "nd"],
};

export default data;
