# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Project: Back Of Your Hand (https://backofyourhand.com)
# Repository: https://github.com/adam-lynch/back-of-your-hand
# Copyright © 2024 Adam Lynch (https://adamlynch.com)

name: lint
on: [push]
defaults:
  run:
    working-directory: ./app
jobs:
  lint-app:
    paths:
      - 'app/**'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint-all--no-fix
